### ISSUE TITLE
Customizable Output Rendering?

### ISSUE THREAD

**Issue by prikhi** [skogsbaer/xmlgen#11]
Hi, love the package & the API you present. I'm currently using it to generate XML that I send to the QuickBooks Desktop SDK. Unfortunately, their XML processor doesn't like where the `xrender` function is sticking newlines and ends up returning an error.

The generated XML looks like this:
```xml
<?qbxml version="13.0"?>
<QBXML
><QBXMLMsgsRq onError="stopOnError"
><AccountQueryRq
></AccountQueryRq
></QBXMLMsgsRq
></QBXML
>
```

I was able to circumvent this by simply filtering out the newline characters so that everything is on a single line, but am wondering if it'd be possible to configure the output the package generates.

It'd be wonderful for debugging if we could also get prettified output like this:
```xml
<?qbxml version="13.0"?>
<QBXML>
    <QBXMLMsgsRq onError="stopOnError">
        <AccountQueryRq>
        </AccountQueryRq>
    </QBXMLMsgsRq>
</QBXML>
```

**Comment by skogsbaer** [comment]
The generated XML that you posted is definitely well-formed, so QuickBooks Desktop SDK should fix their XML parser ;-)

I aggree that pretty printing would be a nice feature. But currently I do not have enough time to implement it. Maybe you could pipe the output of xmlgen through "xmllint --format".

**Comment by gutjuri** [comment]
Well this is definitely a breaking issue for users like me.
I don't understand why the newlines are there in the first place.
If it's for debugging, why must the newlines be right inside a tag?
This makes it very unreadable.

I might have time to fix this in the future though, don't count on me though.
Until then:

![image](https://user-images.githubusercontent.com/23420691/67116779-7686eb80-f1e1-11e9-8530-8c252db50937.png)

Good work on the rest of the library though, thanks guys
